spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?useTimezone=true&serverTimezone=UTC&useSSL=false
    username: root
    password: senha123
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org.springframework.security: DEBUG

